feat: get more info about android fails FGR3-8438

diff --git a/.github/workflows/run-native-tests.yml b/.github/workflows/run-native-tests.yml
--- a/.github/workflows/run-native-tests.yml
+++ b/.github/workflows/run-native-tests.yml
@@ -23,8 +23,13 @@ jobs:
       - name: Install Dependencies
         uses: FigurePOS/github-actions/.github/actions/install-dependencies@v1
 
+      - name: Verify React Native Android Artifacts
+        run: |
+          ls -l node_modules/react-native/android || echo "Directory not found!"
+          ls -l node_modules/react-native/android/com/facebook/react/react-native || echo "Version directory not found!"
+
       - name: Run Android Unit Tests
-        run: cd android && ./gradlew testDebugUnitTest
+        run: cd android && ./gradlew testDebugUnitTest --stacktrace --info
 
   ios:
     runs-on: macos-latest
